@host = http://localhost:5113

### 1. All teams (200)
GET {{host}}/api/teams

### 2. One team by id (200)
GET {{host}}/api/teams/3

### 3. Id that does not exist (404)
GET {{host}}/api/teams/999

### 4. Team not in the list (404)
GET {{host}}/api/teams?name=Viking

### 5. Invalid input (400)
POST {{host}}/api/teams
Content-Type: application/json

{ "name": "" }

### 6. Create team (201)
POST {{host}}/api/teams
Content-Type: application/json

{ "name": "Viking", "stadium": "SR-Bank Arena", "formedYear": 1899 }

### 7. Now it exists (200)
GET {{host}}/api/teams?name=Viking

### 8. Same team again (409)
POST {{host}}/api/teams
Content-Type: application/json

{ "name": "Viking" }